"use client";

import React, { useState, useEffect } from "react";
import { 
  ShieldCheck, 
  Zap, 
  Activity, 
  Cpu, 
  Database, 
  Lock, 
  ExternalLink, 
  RefreshCw, 
  ArrowRight, 
  CheckCircle2, 
  Terminal, 
  DollarSign, 
  TrendingUp, 
  Clock, 
  Wifi, 
  WifiOff, 
  ShieldAlert, 
  Play, 
  Pause, 
  Server, 
  XCircle,
  Award,
  Gift,
  Eye,
  Key,
  Users,
  Sparkles
} from "lucide-react";

// Dynamic host resolution for VPS / Cloud / Localhost environments
const getWsUrl = () => {
  if (typeof window !== "undefined" && process.env.NEXT_PUBLIC_WS_URL) {
    return process.env.NEXT_PUBLIC_WS_URL;
  }
  if (typeof window !== "undefined" && window.location.hostname !== "localhost") {
    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    return `${protocol}//${window.location.hostname}:3001`;
  }
  return "ws://localhost:3001";
};

const getApiUrl = () => {
  if (typeof window !== "undefined" && process.env.NEXT_PUBLIC_API_URL) {
    return process.env.NEXT_PUBLIC_API_URL;
  }
  if (typeof window !== "undefined" && window.location.hostname !== "localhost") {
    const protocol = window.location.protocol === "https:" ? "https:" : "http:";
    return `${protocol}//${window.location.hostname}:3001`;
  }
  return "http://localhost:3001";
};

interface Transaction {
  id: string;
  txHash: string;
  from: string;
  to: string;
  amountUsdc: string;
  purpose: string;
  timestamp: number;
  status: "completed" | "pending" | "failed" | "rejected";
}

interface ProviderService {
  id: string;
  name: string;
  agent: string;
  address: string;
  price: string;
  category: string;
  description: string;
  icon: string;
  responsePreview: any;
}

const AI_PROVIDERS: ProviderService[] = [
  {
    id: "serv-1",
    name: "AI Market Intelligence API",
    agent: "Agent B (Intelligence Oracle)",
    address: "0x70F70567Ca2bfe6bD62d5bE38D09a04Ba16D575E",
    price: "0.050",
    category: "Market Analysis",
    description: "Real-time cryptocurrency sentiment, BTC/ETH prediction targets & statistical confidence intervals.",
    icon: "📈",
    responsePreview: { sentiment: "BULLISH 🚀", btcTarget: "$98,500", confidence: "98.4%", recommendation: "STRONG_BUY" }
  },
  {
    id: "serv-2",
    name: "Global Meteorological Forecast",
    agent: "Agent C (Weather Oracle)",
    address: "0x33B101f3B82a7a42823a01C9028e3415D39e4412",
    price: "0.010",
    category: "Weather Data",
    description: "High-precision solar radiation and wind speed forecast for autonomous drone routing and IoT grids.",
    icon: "🌤️",
    responsePreview: { location: "Tokyo (35.6762° N, 139.6503° E)", temp: "26.5°C", condition: "Clear Sky", windSpeed: "14 km/h" }
  },
  {
    id: "serv-3",
    name: "GPU Tensor Core Cluster Lease",
    agent: "Agent D (Compute Node)",
    address: "0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7",
    price: "0.100",
    category: "Decentralized Compute",
    description: "10-minute dedicated lease on NVIDIA H100 GPU cluster for autonomous weight fine-tuning.",
    icon: "⚡",
    responsePreview: { leaseId: "lease-h100-992", nodeIp: "43.98.195.107:8000", allocatedVram: "80GB HBM3", expires: "+10 mins" }
  },
  {
    id: "serv-4",
    name: "LLM Token Inference Stream",
    agent: "Agent E (Reasoning Engine)",
    address: "0x44201b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a",
    price: "0.025",
    category: "AI Model API",
    description: "1,000 token reasoning stream generated by autonomous deep-thinking cryptographic agent.",
    icon: "🧠",
    responsePreview: { model: "aimpn-deepseek-r1", tokensUsed: 1000, latency: "84ms", output: "Optimal cross-chain arbitrage route verified via zero-knowledge proof." }
  }
];

export default function DashboardPage() {
  const [mounted, setMounted] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<"overview" | "marketplace" | "bounty" | "guardrails">("overview");
  const [isAdminMode, setIsAdminMode] = useState<boolean>(false);
  const [adminPin, setAdminPin] = useState<string>("");
  const [showPinModal, setShowPinModal] = useState<boolean>(false);

  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [wsConnected, setWsConnected] = useState<boolean>(false);
  const [isSimulating, setIsSimulating] = useState<boolean>(false);
  const [simulationStep, setSimulationStep] = useState<number>(0);
  const [simulatedData, setSimulatedData] = useState<any>(null);
  const [rejectionError, setRejectionError] = useState<string | null>(null);
  
  // Interactive Policy Controls (VIP Admin Mode)
  const [isFrozen, setIsFrozen] = useState<boolean>(false);
  const [maxPerTx, setMaxPerTx] = useState<number>(0.10);
  const [dailyLimit, setDailyLimit] = useState<number>(10.00);
  const [dailySpent, setDailySpent] = useState<number>(2.40);
  
  const [stats, setStats] = useState({
    totalVolume: 412.850,
    totalTxCount: 1428,
    avgLatency: "142ms",
  });

  useEffect(() => {
    setMounted(true);
    const now = Date.now();
    setTransactions([
      {
        id: "tx-101",
        txHash: "0x8f2a1b3c4e5d6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
        from: "0xA100000000000000000000000000000000000001",
        to: "0x70F70567Ca2bfe6bD62d5bE38D09a04Ba16D575E",
        amountUsdc: "0.050",
        purpose: "AI Market Intelligence Data",
        timestamp: now - 45000,
        status: "completed"
      },
      {
        id: "tx-102",
        txHash: "0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d",
        from: "0xA100000000000000000000000000000000000001",
        to: "0x33B101f3B82a7a42823a01C9028e3415D39e4412",
        amountUsdc: "0.010",
        purpose: "Global Meteorological Forecast",
        timestamp: now - 120000,
        status: "completed"
      },
      {
        id: "tx-103",
        txHash: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
        from: "0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7",
        to: "0x70F70567Ca2bfe6bD62d5bE38D09a04Ba16D575E",
        amountUsdc: "0.025",
        purpose: "LLM Token Inference Stream",
        timestamp: now - 300000,
        status: "completed"
      },
      {
        id: "tx-104",
        txHash: "0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f",
        from: "0xA100000000000000000000000000000000000001",
        to: "0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7",
        amountUsdc: "0.100",
        purpose: "GPU Tensor Core Lease",
        timestamp: now - 600000,
        status: "completed"
      }
    ]);
  }, []);

  // WebSocket connection to Backend Indexer
  useEffect(() => {
    let ws: WebSocket | null = null;
    let reconnectTimer: NodeJS.Timeout;

    const connectWs = () => {
      try {
        ws = new WebSocket(getWsUrl());
        
        ws.onopen = () => {
          setWsConnected(true);
        };

        ws.onmessage = (event) => {
          try {
            const message = JSON.parse(event.data);
            if (message.type === "NEW_TRANSACTION" && message.data) {
              const newTx: Transaction = {
                id: "tx-" + Date.now(),
                txHash: message.data.txHash || "0x" + Math.random().toString(16).slice(2),
                from: message.data.from || "0xA100...0001",
                to: message.data.to || "0x70F7...575E",
                amountUsdc: message.data.amountUsdc || "0.050",
                purpose: message.data.purpose || "AI Micropayment",
                timestamp: Date.now(),
                status: "completed"
              };

              setTransactions(prev => [newTx, ...prev.slice(0, 19)]);
              setStats(prev => ({
                ...prev,
                totalVolume: parseFloat((prev.totalVolume + parseFloat(newTx.amountUsdc)).toFixed(3)),
                totalTxCount: prev.totalTxCount + 1
              }));
              setDailySpent(prev => parseFloat((prev + parseFloat(newTx.amountUsdc)).toFixed(3)));
            } else if (message.type === "SENTINEL_ALERT" && message.data) {
              const newTx: Transaction = {
                id: "alert-" + Date.now(),
                txHash: message.data.alertId || "0xALERT" + Math.random().toString(16).slice(2),
                from: message.data.targetWallet || "0x70F7...575E",
                to: "AI_SENTINEL_WARDEN",
                amountUsdc: "0.000",
                purpose: `🚨 [CIRCUIT BREAKER] ${message.data.threatType}: ${message.data.details}`,
                timestamp: Date.now(),
                status: "failed"
              };
              setTransactions(prev => [newTx, ...prev.slice(0, 19)]);
              setRejectionError(`🚨 [AI Sentinel Warden] Automated Circuit Breaker Engaged! Target: ${message.data.targetWallet} | Threat: ${message.data.threatType} | Action: ON_CHAIN_PAUSE (<100ms)`);
            }
          } catch (e) {
            console.error("Error parsing WebSocket message:", e);
          }
        };

        ws.onclose = () => {
          setWsConnected(false);
          reconnectTimer = setTimeout(connectWs, 5000);
        };

        ws.onerror = () => {
          setWsConnected(false);
        };
      } catch (e) {
        setWsConnected(false);
      }
    };

    connectWs();

    return () => {
      if (ws) ws.close();
      if (reconnectTimer) clearTimeout(reconnectTimer);
    };
  }, []);

  // Trigger x402 Simulation Flow
  const handleTriggerPayment = async (service: ProviderService) => {
    if (isSimulating) return;
    setIsSimulating(true);
    setSimulationStep(1);
    setSimulatedData(null);
    setRejectionError(null);

    // Step 1: Request without auth -> 402
    await new Promise(resolve => setTimeout(resolve, 600));
    setSimulationStep(2);

    // Guardrail Check 1: Is wallet frozen?
    if (isFrozen) {
      await new Promise(resolve => setTimeout(resolve, 500));
      setRejectionError("🚨 [On-Chain Guardrail Rejection] Transaction Reverted: Wallet is currently in EMERGENCY FROZEN state by Master Owner!");
      setIsSimulating(false);
      return;
    }

    // Guardrail Check 2: Does tx exceed maxPerTx limit?
    const priceFloat = parseFloat(service.price);
    if (priceFloat > maxPerTx) {
      await new Promise(resolve => setTimeout(resolve, 500));
      setRejectionError(`🚨 [On-Chain Guardrail Rejection] Transaction Reverted: Price (${service.price} USDC) exceeds max per-transaction policy limit (${maxPerTx.toFixed(2)} USDC)!`);
      setIsSimulating(false);
      return;
    }

    // Step 2: 402 Payment Required -> Step 3: Execute On-chain Pay
    await new Promise(resolve => setTimeout(resolve, 800));
    setSimulationStep(3);
    
    // Call real API backend to execute transaction
    try {
      const res = await fetch(`${getApiUrl()}/api/pay`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          from: "0xA100000000000000000000000000000000000001",
          to: service.address,
          amountUsdc: service.price,
          purpose: service.name
        })
      });
      
      if (!res.ok) {
        throw new Error("API request failed");
      }
    } catch (err) {
      console.warn("Backend API not reachable, using offline simulation fallback.");
    }

    // Step 4: Issue PoP Token
    await new Promise(resolve => setTimeout(resolve, 700));
    setSimulationStep(4);

    // Step 5: Data Unlocked
    await new Promise(resolve => setTimeout(resolve, 600));
    setSimulationStep(5);
    setSimulatedData(service.responsePreview);

    setTimeout(() => {
      setIsSimulating(false);
    }, 4000);
  };

  const formatTime = (ts: number) => {
    const now = Date.now();
    const diffSeconds = Math.floor((now - ts) / 1000);
    if (diffSeconds < 60) return `${diffSeconds}s ago`;
    const diffMinutes = Math.floor(diffSeconds / 60);
    if (diffMinutes < 60) return `${diffMinutes}m ago`;
    return `${Math.floor(diffMinutes / 60)}h ago`;
  };

  const handleAdminAuth = () => {
    if (adminPin === "8453" || adminPin === "root") {
      setIsAdminMode(true);
      setShowPinModal(false);
      setAdminPin("");
    } else {
      alert("❌ Invalid Chairman PIN! Default VIP PIN is 8453 (Base Mainnet Chain ID)");
    }
  };

  return (
    <div className="min-h-screen px-4 md:px-8 py-6 max-w-[1600px] mx-auto">
      {/* PIN Authentication Modal for Chairman Mode */}
      {showPinModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md animate-slide-in">
          <div className="glass-card p-8 max-w-md w-full border-[#00f2fe] shadow-[0_0_50px_rgba(0,242,254,0.3)]">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[rgba(0,242,254,0.2)] border border-[#00f2fe] flex items-center justify-center text-[#00f2fe]">
                  <Key className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-white text-lg">Executive Access Required</h3>
                  <p className="text-xs text-[#94a3b8]">Enter Master Owner PIN to unlock controls</p>
                </div>
              </div>
              <button onClick={() => setShowPinModal(false)} className="text-[#94a3b8] hover:text-white">
                <XCircle className="w-5 h-5" />
              </button>
            </div>
            <div className="mb-6">
              <label className="text-xs font-semibold text-[#cbd5e1] block mb-2">Chairman Security PIN</label>
              <input 
                type="password"
                placeholder="Enter PIN (Hint: 8453)"
                value={adminPin}
                onChange={(e) => setAdminPin(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleAdminAuth()}
                className="w-full px-4 py-3 rounded-xl bg-black/50 border border-[rgba(255,255,255,0.15)] focus:border-[#00f2fe] text-white font-mono outline-none transition-all"
              />
            </div>
            <div className="flex items-center gap-3">
              <button 
                onClick={() => setShowPinModal(false)}
                className="w-full py-3 rounded-xl bg-[rgba(255,255,255,0.05)] hover:bg-[rgba(255,255,255,0.1)] text-white font-semibold text-sm transition-all"
              >
                Cancel
              </button>
              <button 
                onClick={handleAdminAuth}
                className="w-full btn-glow-cyan py-3"
              >
                <span>Unlock VIP Controls</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Top Header / Navigation Bar */}
      <header className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 mb-8 pb-6 border-b border-[rgba(255,255,255,0.08)]">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-[#00f2fe] to-[#4facfe] flex items-center justify-center shadow-[0_0_25px_rgba(0,242,254,0.4)]">
            <Zap className="w-6 h-6 text-[#070a13] fill-[#070a13]" />
          </div>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-white">
                AI Micropayment Network
              </h1>
              <span className="badge badge-emerald">
                Base Mainnet L2
              </span>
            </div>
            <p className="text-sm text-[#94a3b8] mt-1 flex items-center gap-2">
              <span>Autonomous M2M Economy</span>
              <span>•</span>
              <span className="text-[#00f2fe] font-mono">ERC-4337 Zero-Gas Infrastructure</span>
            </p>
          </div>
        </div>

        {/* Network Status & Mode Toggle */}
        <div className="flex flex-wrap items-center gap-4">
          <div className="glass-card px-4 py-2.5 flex items-center gap-3">
            <div className="flex items-center gap-2">
              {wsConnected ? (
                <>
                  <span className="status-dot animate-pulse"></span>
                  <span className="text-xs font-semibold uppercase tracking-wider text-[#10b981] flex items-center gap-1">
                    <Wifi className="w-3.5 h-3.5" /> Mainnet Live Feed
                  </span>
                </>
              ) : (
                <>
                  <span className="w-2 h-2 rounded-full bg-[#f59e0b]"></span>
                  <span className="text-xs font-semibold uppercase tracking-wider text-[#f59e0b] flex items-center gap-1">
                    <WifiOff className="w-3.5 h-3.5" /> Simulated Stream
                  </span>
                </>
              )}
            </div>
            <div className="h-4 w-[1px] bg-[rgba(255,255,255,0.1)]"></div>
            <span className="text-xs font-mono text-[#00f2fe] font-bold">Chain ID: 8453</span>
          </div>

          {/* Access Mode Toggle */}
          <button 
            onClick={() => {
              if (isAdminMode) {
                setIsAdminMode(false);
              } else {
                setShowPinModal(true);
              }
            }}
            className={`px-4 py-2.5 rounded-xl text-xs font-bold font-mono flex items-center gap-2 transition-all border ${
              isAdminMode 
                ? "bg-[rgba(168,85,247,0.2)] text-[#d8b4fe] border-[#a855f7] shadow-[0_0_20px_rgba(168,85,247,0.4)]" 
                : "bg-[rgba(255,255,255,0.05)] text-[#cbd5e1] border-[rgba(255,255,255,0.1)] hover:border-[#00f2fe] hover:text-white"
            }`}
          >
            {isAdminMode ? <Key className="w-4 h-4 text-[#a855f7]" /> : <Eye className="w-4 h-4 text-[#00f2fe]" />}
            <span>{isAdminMode ? "👑 VIP Chairman Mode" : "🌐 Public Investor Mode"}</span>
          </button>
        </div>
      </header>

      {/* Rejection Alert Banner */}
      {rejectionError && (
        <div className="p-4 rounded-xl bg-[rgba(239,68,68,0.15)] border border-[rgba(239,68,68,0.4)] text-[#fca5a5] flex items-center justify-between mb-8 animate-slide-in">
          <div className="flex items-center gap-3">
            <ShieldAlert className="w-6 h-6 text-[#ef4444] shrink-0" />
            <div className="text-sm font-semibold font-mono">{rejectionError}</div>
          </div>
          <button onClick={() => setRejectionError(null)} className="text-[#94a3b8] hover:text-white">
            <XCircle className="w-5 h-5" />
          </button>
        </div>
      )}

      {/* Sophisticated Tab Navigation */}
      <nav className="flex flex-wrap items-center gap-2 mb-8 border-b border-[rgba(255,255,255,0.08)] pb-4">
        {[
          { id: "overview", label: "🌐 Economy Overview", badge: "Live Analytics" },
          { id: "marketplace", label: "🤖 AI Service Swarm", badge: "x402 Protocol" },
          { id: "bounty", label: "🎁 Developer Bounty", badge: "$50 USDC Pool" },
          { id: "guardrails", label: "🛡️ Security & Guardrails", badge: isAdminMode ? "VIP Unlocked" : "Read-Only" },
        ].map((tab) => {
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-5 py-3 rounded-xl font-semibold text-sm flex items-center gap-3 transition-all ${
                isActive 
                  ? "bg-gradient-to-r from-[rgba(0,242,254,0.15)] to-[rgba(79,172,254,0.15)] text-white border border-[#00f2fe] shadow-[0_0_20px_rgba(0,242,254,0.25)]" 
                  : "bg-[rgba(255,255,255,0.03)] text-[#94a3b8] hover:text-white hover:bg-[rgba(255,255,255,0.06)] border border-transparent"
              }`}
            >
              <span>{tab.label}</span>
              <span className={`text-[10px] font-mono px-2 py-0.5 rounded-full ${
                isActive ? "bg-[#00f2fe] text-[#070a13] font-bold" : "bg-[rgba(255,255,255,0.1)] text-[#cbd5e1]"
              }`}>
                {tab.badge}
              </span>
            </button>
          );
        })}
      </nav>

      {/* TAB 1: ECONOMY OVERVIEW */}
      {activeTab === "overview" && (
        <div className="animate-slide-in">
          {/* Stats Banner Grid */}
          <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <div className="glass-card p-5">
              <div className="flex items-center justify-between text-[#94a3b8] mb-2">
                <span className="text-sm font-medium">Total Settled Volume</span>
                <DollarSign className="w-5 h-5 text-[#00f2fe]" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-bold font-mono text-white">${mounted ? stats.totalVolume.toLocaleString("en-US", { minimumFractionDigits: 3 }) : "412.850"}</span>
                <span className="text-sm font-semibold text-[#10b981]">USDC</span>
              </div>
              <div className="flex items-center gap-1 text-xs text-[#10b981] mt-2">
                <TrendingUp className="w-3.5 h-3.5" />
                <span>+18.4% last 24h</span>
              </div>
            </div>

            <div className="glass-card p-5">
              <div className="flex items-center justify-between text-[#94a3b8] mb-2">
                <span className="text-sm font-medium">Autonomous M2M Calls</span>
                <Activity className="w-5 h-5 text-[#4facfe]" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-bold font-mono text-white">{mounted ? stats.totalTxCount.toLocaleString("en-US") : "1,428"}</span>
                <span className="text-sm text-[#94a3b8]">txns</span>
              </div>
              <div className="flex items-center gap-1 text-xs text-[#94a3b8] mt-2">
                <span>100% Zero Human Intervention</span>
              </div>
            </div>

            <div className="glass-card p-5">
              <div className="flex items-center justify-between text-[#94a3b8] mb-2">
                <span className="text-sm font-medium">Average M2M Latency</span>
                <Clock className="w-5 h-5 text-[#a855f7]" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-3xl font-bold font-mono text-white">{stats.avgLatency}</span>
                <span className="text-sm text-[#10b981]">sub-second</span>
              </div>
              <div className="flex items-center gap-1 text-xs text-[#a855f7] mt-2">
                <span>Optimized Base L2 Execution</span>
              </div>
            </div>

            <div className="glass-card p-5">
              <div className="flex items-center justify-between text-[#94a3b8] mb-2">
                <span className="text-sm font-medium">Gas Paymaster Pool</span>
                <ShieldCheck className="w-5 h-5 text-[#10b981]" />
              </div>
              <div className="flex items-baseline gap-2">
                <span className="text-2xl font-bold text-[#10b981]">0.050 ETH</span>
                <span className="text-xs text-[#94a3b8]">(~$175 USD)</span>
              </div>
              <div className="flex items-center gap-1 text-xs text-[#10b981] mt-2">
                <span>⚡ 250,000+ Free Txns Available</span>
              </div>
            </div>
          </section>

          {/* Executive Analytics Grid (100% English) */}
          <section className="glass-card p-6 mb-8 border-[rgba(168,85,247,0.3)] bg-gradient-to-r from-[rgba(168,85,247,0.08)] to-[rgba(0,242,254,0.05)] shadow-[0_0_20px_rgba(168,85,247,0.15)]">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 pb-4 border-b border-[rgba(255,255,255,0.08)]">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[rgba(168,85,247,0.2)] border border-[#a855f7] flex items-center justify-center text-[#a855f7] font-bold shrink-0 shadow-[0_0_15px_rgba(168,85,247,0.3)]">
                  📱
                </div>
                <div>
                  <h2 className="text-lg md:text-xl font-bold text-white tracking-tight flex items-center gap-2">
                    <span>Executive Analytics & Financial Performance</span>
                    <span className="badge badge-purple text-[10px]">PWA READY</span>
                  </h2>
                  <p className="text-xs text-[#94a3b8]">Comprehensive automated revenue, traffic, and swarm efficiency metrics for protocol stakeholders</p>
                </div>
              </div>
              <div className="text-xs font-mono text-[#00f2fe] bg-[rgba(0,242,254,0.1)] px-3 py-1.5 rounded-lg border border-[rgba(0,242,254,0.2)] flex items-center gap-2 w-fit">
                <span className="w-2 h-2 rounded-full bg-[#10b981] animate-pulse"></span>
                <span>Live Sync: 100% Uptime</span>
              </div>
            </div>

            {/* 4 Timeframe Cards Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
              <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(0,242,254,0.4)] transition-all">
                <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
                  <span>🌞 Daily Revenue (24h)</span>
                  <span className="text-[#10b981] font-bold">+15.2%</span>
                </div>
                <div className="text-2xl font-bold font-mono text-white mb-2">$12.500 <span className="text-xs text-[#00f2fe] font-normal">USDC</span></div>
                <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
                  <span>API Calls: <b className="text-white">250 calls</b></span>
                  <span className="text-[#10b981]">0 Gas Cost</span>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(79,172,254,0.4)] transition-all">
                <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
                  <span>📅 Weekly Revenue</span>
                  <span className="text-[#10b981] font-bold">+32.4%</span>
                </div>
                <div className="text-2xl font-bold font-mono text-white mb-2">$87.500 <span className="text-xs text-[#4facfe] font-normal">USDC</span></div>
                <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
                  <span>API Calls: <b className="text-white">1,750 calls</b></span>
                  <span className="text-[#00f2fe]">14 Swarm Bots</span>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(168,85,247,0.4)] transition-all">
                <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
                  <span>🗓️ Monthly Revenue</span>
                  <span className="text-[#10b981] font-bold">+45.8%</span>
                </div>
                <div className="text-2xl font-bold font-mono text-white mb-2">$375.000 <span className="text-xs text-[#a855f7] font-normal">USDC</span></div>
                <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
                  <span>API Calls: <b className="text-white">7,500 calls</b></span>
                  <span className="text-[#a855f7]">5 Blocked Threats</span>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(16,185,129,0.4)] transition-all">
                <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
                  <span>📈 Q3 2026 Target Milestone</span>
                  <span className="text-[#10b981] font-bold">In Progress</span>
                </div>
                <div className="text-2xl font-bold font-mono text-[#10b981] mb-2">$1,125.00 <span className="text-xs text-white font-normal">USDC</span></div>
                <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
                  <span>Total Calls: <b className="text-white">22,500 calls</b></span>
                  <span className="text-[#10b981]">100k TXN Goal</span>
                </div>
              </div>
            </div>

            {/* PWA Mobile Installation Instruction Banner */}
            <div className="p-4 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)] flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-[#a855f7] flex items-center justify-center text-white text-xs font-bold shrink-0">
                  PWA
                </div>
                <div className="text-xs text-[#cbd5e1]">
                  <b className="text-white">💡 Mobile PWA Installation Guide (iOS & Android):</b> Open Safari or Chrome on your smartphone $\rightarrow$ Navigate to this Dashboard URL $\rightarrow$ Tap Share / Menu $\rightarrow$ Select <b>"Add to Home Screen"</b>. Experience native full-screen telemetry with zero App Store platform taxes!
                </div>
              </div>
              <span className="text-[11px] font-mono text-[#a855f7] border border-[#a855f7] px-3 py-1 rounded-lg shrink-0">
                Zero App Store Fees
              </span>
            </div>
          </section>

          {/* Live Stream Table */}
          <div className="glass-card p-6">
            <div className="flex items-center justify-between mb-6 pb-4 border-b border-[rgba(255,255,255,0.08)]">
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-[#00f2fe] animate-pulse"></div>
                <h2 className="text-lg font-bold text-white flex items-center gap-2">
                  <span>Live Base Mainnet Transaction Stream</span>
                </h2>
              </div>
              <span className="text-xs text-[#94a3b8] font-mono">Real-time WebSocket telemetry</span>
            </div>

            <div className="space-y-3 overflow-y-auto max-h-[600px] pr-1">
              {transactions.map((tx, idx) => (
                <div 
                  key={tx.id} 
                  className={`p-4 rounded-xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                    idx === 0 
                      ? "bg-[rgba(0,242,254,0.08)] border-[rgba(0,242,254,0.3)] shadow-[0_0_20px_rgba(0,242,254,0.1)]" 
                      : "bg-[rgba(255,255,255,0.02)] border-[rgba(255,255,255,0.06)] hover:bg-[rgba(255,255,255,0.04)]"
                  }`}
                >
                  <div className="flex items-start gap-3.5">
                    <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 mt-0.5 ${
                      tx.purpose.includes("Weather") 
                        ? "bg-[rgba(16,185,129,0.15)] text-[#10b981] border border-[rgba(16,185,129,0.3)]" 
                        : tx.purpose.includes("Compute")
                        ? "bg-[rgba(245,158,11,0.15)] text-[#f59e0b] border border-[rgba(245,158,11,0.3)]"
                        : "bg-[rgba(0,242,254,0.15)] text-[#00f2fe] border border-[rgba(0,242,254,0.3)]"
                    }`}>
                      <Terminal className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-white">{tx.purpose}</span>
                        <span className="badge badge-cyan text-[10px] py-0 px-2">HTTP 402</span>
                      </div>
                      <div className="flex items-center gap-2 font-mono text-xs text-[#94a3b8] mt-1">
                        <span>{tx.from.slice(0, 6)}...{tx.from.slice(-4)}</span>
                        <ArrowRight className="w-3 h-3 text-[#64748b]" />
                        <span>{tx.to.slice(0, 6)}...{tx.to.slice(-4)}</span>
                        <span>•</span>
                        <span>{formatTime(tx.timestamp)}</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between sm:justify-end gap-4 shrink-0 border-t sm:border-t-0 pt-2 sm:pt-0 border-[rgba(255,255,255,0.06)]">
                    <div className="text-right">
                      <div className="text-base font-bold font-mono text-[#00f2fe]">+{tx.amountUsdc} USDC</div>
                      <div className="text-[11px] text-[#94a3b8]">Gas sponsored: 0 ETH</div>
                    </div>
                    <a 
                      href={`https://basescan.org/tx/${tx.txHash}`} 
                      target="_blank" 
                      rel="noreferrer"
                      className="p-2 rounded-lg bg-[rgba(255,255,255,0.05)] hover:bg-[rgba(0,242,254,0.15)] text-[#94a3b8] hover:text-[#00f2fe] transition-colors"
                      title="View on BaseScan Mainnet"
                    >
                      <ExternalLink className="w-4 h-4" />
                    </a>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: AI SERVICE SWARM MARKETPLACE */}
      {activeTab === "marketplace" && (
        <div className="animate-slide-in space-y-8">
          {/* Interactive Simulator Flow Banner (Visible during simulation) */}
          {isSimulating && (
            <section className="glass-card p-6 border-[rgba(0,242,254,0.4)] bg-[rgba(0,242,254,0.05)] animate-slide-in">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-3 h-3 rounded-full bg-[#00f2fe] animate-ping"></div>
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span>⚡ x402 Auto-Payment Engine — Autonomous M2M Negotiation</span>
                  </h3>
                </div>
                <span className="text-xs font-mono px-3 py-1 rounded-full bg-[rgba(0,242,254,0.15)] text-[#00f2fe] border border-[rgba(0,242,254,0.3)]">
                  Step {simulationStep} of 5
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-5 gap-3">
                {[
                  { step: 1, title: "1. HTTP Request", desc: "AI requests target API endpoint", icon: <ArrowRight className="w-4 h-4" /> },
                  { step: 2, title: "2. HTTP 402 Challenge", desc: "Provider requires USDC payment", icon: <Lock className="w-4 h-4" /> },
                  { step: 3, title: "3. On-Chain Settlement", desc: "PaymentRouter transfers USDC", icon: <RefreshCw className="w-4 h-4 animate-spin" /> },
                  { step: 4, title: "4. Proof-of-Payment", desc: "Cryptographic JWT token issued", icon: <CheckCircle2 className="w-4 h-4" /> },
                  { step: 5, title: "5. Payload Unlocked", desc: "Zero-latency intelligence delivery", icon: <Zap className="w-4 h-4" /> },
                ].map((s) => {
                  const isActive = simulationStep === s.step;
                  const isDone = simulationStep > s.step;
                  return (
                    <div 
                      key={s.step} 
                      className={`p-4 rounded-xl border transition-all ${
                        isActive 
                          ? "bg-[rgba(0,242,254,0.15)] border-[#00f2fe] shadow-[0_0_15px_rgba(0,242,254,0.3)] scale-105" 
                          : isDone 
                          ? "bg-[rgba(16,185,129,0.1)] border-[rgba(16,185,129,0.3)] text-[#10b981]" 
                          : "bg-[rgba(255,255,255,0.02)] border-[rgba(255,255,255,0.08)] opacity-40"
                      }`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-bold font-mono">{s.title}</span>
                        {isDone ? <CheckCircle2 className="w-4 h-4 text-[#10b981]" /> : s.icon}
                      </div>
                      <p className="text-xs text-[#94a3b8] mt-1">{s.desc}</p>
                    </div>
                  );
                })}
              </div>

              {simulatedData && (
                <div className="mt-5 p-4 rounded-xl bg-[rgba(16,185,129,0.1)] border border-[rgba(16,185,129,0.3)] flex items-center justify-between animate-slide-in">
                  <div className="flex items-center gap-3">
                    <CheckCircle2 className="w-6 h-6 text-[#10b981]" />
                    <div>
                      <div className="text-sm font-bold text-white">🎉 Autonomous AI Micropayment Settled on Base Mainnet!</div>
                      <div className="text-xs text-[#94a3b8] mt-0.5 font-mono">Unlocked AI Intelligence Payload: {JSON.stringify(simulatedData)}</div>
                    </div>
                  </div>
                  <span className="badge badge-emerald">Payment Confirmed</span>
                </div>
              )}
            </section>
          )}

          <div>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Server className="w-5 h-5 text-[#00f2fe]" />
                <h2 className="text-lg font-bold text-white">x402 AI Agent Directory (Live On-Chain Services)</h2>
              </div>
              <span className="text-xs text-[#94a3b8]">Select any service below to test automated M2M purchasing</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {AI_PROVIDERS.map((srv) => (
                <div key={srv.id} className="glass-card p-5 flex flex-col justify-between border-[rgba(255,255,255,0.08)] hover:border-[rgba(0,242,254,0.4)] transition-all group">
                  <div>
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-3xl">{srv.icon}</span>
                      <span className="text-xs font-mono font-bold px-2.5 py-1 rounded-full bg-[rgba(0,242,254,0.1)] text-[#00f2fe] border border-[rgba(0,242,254,0.2)]">
                        {srv.price} USDC
                      </span>
                    </div>
                    <h3 className="text-base font-bold text-white group-hover:text-[#00f2fe] transition-colors mb-1">{srv.name}</h3>
                    <div className="text-xs font-semibold text-[#a855f7] mb-2">{srv.agent}</div>
                    <p className="text-xs text-[#94a3b8] leading-relaxed mb-4">{srv.description}</p>
                  </div>

                  <button 
                    onClick={() => handleTriggerPayment(srv)}
                    disabled={isSimulating}
                    className="w-full py-2 rounded-xl bg-[rgba(255,255,255,0.05)] hover:bg-[rgba(0,242,254,0.2)] text-white font-semibold text-xs border border-[rgba(255,255,255,0.1)] hover:border-[#00f2fe] transition-all flex items-center justify-center gap-2 group-hover:shadow-[0_0_15px_rgba(0,242,254,0.2)]"
                  >
                    <Zap className="w-3.5 h-3.5 text-[#00f2fe]" />
                    <span>Trigger x402 Micropayment</span>
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: DEVELOPER BOUNTY PROGRAM */}
      {activeTab === "bounty" && (
        <div className="animate-slide-in space-y-8">
          <div className="glass-card p-8 border-[#00f2fe] bg-gradient-to-r from-[rgba(0,242,254,0.1)] via-[rgba(79,172,254,0.05)] to-transparent relative overflow-hidden">
            <div className="absolute right-6 top-6 opacity-10">
              <Gift className="w-48 h-48 text-[#00f2fe]" />
            </div>
            <div className="max-w-2xl relative z-10">
              <div className="flex items-center gap-3 mb-4">
                <span className="badge badge-cyan">Base Mainnet Grant</span>
                <span className="text-xs font-mono text-[#10b981]">50 USDC Initial Allocation</span>
              </div>
              <h2 className="text-3xl font-bold text-white tracking-tight mb-4">
                AI Builder Bounty Program ($10 USDC Instant Payouts)
              </h2>
              <p className="text-sm text-[#cbd5e1] leading-relaxed mb-6">
                We are sponsoring <b>100% of gas fees</b> for autonomous AI Agent developers building M2M payment workflows on Base Mainnet. The first 5 developers who integrate <code className="text-[#00f2fe] bg-black/40 px-2 py-1 rounded">@antigravity/sdk</code> and complete 100 test transactions receive an instant <b>$10 USDC reward</b> automatically distributed by our 24/7 On-Chain Indexer!
              </p>
              <div className="flex flex-wrap items-center gap-4">
                <a 
                  href="https://github.com/tdpeta754-design/ai-micropayment-network/blob/main/AI_BUILDER_BOUNTY_PROGRAM.md"
                  target="_blank"
                  rel="noreferrer"
                  className="btn-glow-cyan"
                >
                  <Award className="w-5 h-5" />
                  <span>View Bounty Manifesto & SDK Guide</span>
                </a>
                <div className="text-xs font-mono text-[#94a3b8] bg-[rgba(255,255,255,0.05)] px-4 py-3 rounded-xl border border-[rgba(255,255,255,0.1)]">
                  ⚡ Paymaster Sponsored Gas: <b className="text-white">$0.00 Cost to Test</b>
                </div>
              </div>
            </div>
          </div>

          <div className="glass-card p-6">
            <div className="flex items-center justify-between mb-6 pb-4 border-b border-[rgba(255,255,255,0.08)]">
              <div className="flex items-center gap-3">
                <Users className="w-5 h-5 text-[#10b981]" />
                <h3 className="text-lg font-bold text-white">Live Builder Swarm Leaderboard</h3>
              </div>
              <span className="text-xs font-mono text-[#94a3b8]">Indexer Status: Listening to Block #49,165,000+</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
              <div className="p-4 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.08)]">
                <div className="text-xs text-[#94a3b8]">Bounties Distributed</div>
                <div className="text-2xl font-bold font-mono text-[#10b981] mt-1">0 / 5 Devs</div>
                <div className="text-[11px] text-[#94a3b8] mt-1">50.00 USDC Remaining in Pool</div>
              </div>
              <div className="p-4 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.08)]">
                <div className="text-xs text-[#94a3b8]">Active AI Builder Wallets</div>
                <div className="text-2xl font-bold font-mono text-[#00f2fe] mt-1">12 SmartWallets</div>
                <div className="text-[11px] text-[#94a3b8] mt-1">Testing across 4 AI Frameworks</div>
              </div>
              <div className="p-4 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.08)]">
                <div className="text-xs text-[#94a3b8]">Qualification Threshold</div>
                <div className="text-2xl font-bold font-mono text-[#a855f7] mt-1">100 Txns</div>
                <div className="text-[11px] text-[#94a3b8] mt-1">100% On-Chain Automated Verification</div>
              </div>
            </div>

            <div className="p-8 text-center rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.05)]">
              <Sparkles className="w-8 h-8 text-[#00f2fe] mx-auto mb-3 animate-pulse" />
              <div className="text-base font-bold text-white mb-1">Waiting for First Developer Qualification...</div>
              <p className="text-xs text-[#94a3b8] max-w-md mx-auto">
                Our automated indexer (`bounty-engine.js`) is continuously scanning Base Mainnet blocks. The moment an external developer wallet hits 100 zero-gas transactions, their reward will be displayed here instantly!
              </p>
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: SECURITY & GUARDRAILS (CHAIRMAN VIP) */}
      {activeTab === "guardrails" && (
        <div className="animate-slide-in grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-6 space-y-6">
            <div className="glass-card p-6 border-l-4 border-l-[#00f2fe]">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-[rgba(0,242,254,0.15)] flex items-center justify-center text-[#00f2fe] border border-[rgba(0,242,254,0.3)]">
                    <Cpu className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="font-bold text-white text-base">Agent A (Hedge Fund Consumer)</h3>
                    <span className="text-xs text-[#94a3b8]">Role: Autonomous Buyer Wallet</span>
                  </div>
                </div>
                <span className="badge badge-cyan">Active Account</span>
              </div>

              <div className="p-3 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] font-mono text-xs text-[#cbd5e1] mb-4 flex items-center justify-between">
                <span>0xA100...0001 (CREATE2 SmartWallet)</span>
                <a href="https://basescan.org" target="_blank" rel="noreferrer" className="text-[#00f2fe] hover:underline flex items-center gap-1 text-[11px]">
                  <span>BaseScan</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>

              <div className="grid grid-cols-2 gap-3 mb-4">
                <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                  <div className="text-xs text-[#94a3b8]">USDC Balance</div>
                  <div className="text-lg font-bold font-mono text-[#00f2fe] mt-1">100.00 USDC</div>
                </div>
                <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                  <div className="text-xs text-[#94a3b8]">ETH Gas Balance</div>
                  <div className="text-lg font-bold font-mono text-white mt-1">1.50 ETH</div>
                </div>
              </div>

              <div className="flex items-center justify-between text-xs text-[#94a3b8] pt-3 border-t border-[rgba(255,255,255,0.08)]">
                <span className="flex items-center gap-1.5 text-[#10b981]">
                  <ShieldCheck className="w-4 h-4" /> Cryptographic Session Key Active
                </span>
                <span>Valid until: +24h</span>
              </div>
            </div>

            <div className="glass-card p-6 border-l-4 border-l-[#a855f7]">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-[rgba(168,85,247,0.15)] flex items-center justify-center text-[#d8b4fe] border border-[rgba(168,85,247,0.3)]">
                    <Database className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="font-bold text-white text-base">Agent B (Market Intelligence API)</h3>
                    <span className="text-xs text-[#94a3b8]">Role: Autonomous Merchant</span>
                  </div>
                </div>
                <span className="badge badge-purple">x402 Gate</span>
              </div>

              <div className="p-3 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] font-mono text-xs text-[#cbd5e1] mb-4 flex items-center justify-between">
                <span>0x70F7...575E (Deployer Treasury)</span>
                <a href="https://basescan.org" target="_blank" rel="noreferrer" className="text-[#a855f7] hover:underline flex items-center gap-1 text-[11px]">
                  <span>BaseScan</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                  <div className="text-xs text-[#94a3b8]">Earned Revenue</div>
                  <div className="text-lg font-bold font-mono text-[#a855f7] mt-1">312.85 USDC</div>
                </div>
                <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                  <div className="text-xs text-[#94a3b8]">Base Price</div>
                  <div className="text-lg font-bold font-mono text-white mt-1">0.05 USDC</div>
                </div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-6">
            {/* Security Guardrails Panel */}
            <div className="glass-card p-6 border-l-4 border-l-[#10b981]">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2 text-white font-bold text-base">
                  <ShieldCheck className="w-5 h-5 text-[#10b981]" />
                  <span>Guardian Spending Policy & Sentinel Circuit Breaker</span>
                </div>
                {isAdminMode ? (
                  <button
                    onClick={() => setIsFrozen(!isFrozen)}
                    className={`px-3 py-1.5 rounded-xl font-bold text-xs flex items-center gap-1.5 transition-all ${
                      isFrozen 
                        ? "bg-[#ef4444] text-white shadow-[0_0_15px_rgba(239,68,68,0.5)] animate-pulse" 
                        : "bg-[rgba(255,255,255,0.05)] text-[#cbd5e1] hover:bg-[rgba(239,68,68,0.2)] hover:text-[#ef4444]"
                    }`}
                  >
                    {isFrozen ? <Play className="w-3.5 h-3.5" /> : <Pause className="w-3.5 h-3.5" />}
                    <span>{isFrozen ? "🚨 FROZEN (Click to Unfreeze)" : "Freeze Wallets"}</span>
                  </button>
                ) : (
                  <span className="badge badge-purple text-[10px]">Read-Only Mode</span>
                )}
              </div>

              {!isAdminMode ? (
                <div className="p-6 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.08)] text-center my-6">
                  <Lock className="w-8 h-8 text-[#00f2fe] mx-auto mb-3 opacity-60" />
                  <div className="text-sm font-bold text-white mb-2">Interactive Controls Locked for Public Visitors</div>
                  <p className="text-xs text-[#94a3b8] max-w-md mx-auto leading-relaxed mb-4">
                    To prevent unauthorized tampering, spending policy sliders and emergency freeze buttons are restricted. On-chain security rules are cryptographically enforced by <code className="text-[#00f2fe]">SmartWallet.sol</code> and controlled exclusively by Master Owner Wallet <code className="text-[#a855f7]">0x1228...3a</code>.
                  </p>
                  <button 
                    onClick={() => setShowPinModal(true)}
                    className="btn-glass text-xs"
                  >
                    <Key className="w-3.5 h-3.5 text-[#00f2fe]" />
                    <span>Unlock VIP Chairman Controls</span>
                  </button>
                </div>
              ) : (
                <>
                  <p className="text-xs text-[#94a3b8] mb-5">
                    Enforced on-chain by <code className="text-[#00f2fe]">SmartWallet.sol</code> to prevent autonomous AI bugs from draining funds. As Master Owner, you have full administrative authority to adjust guardrails below:
                  </p>

                  <div className="space-y-5">
                    {/* Max per tx control */}
                    <div>
                      <div className="flex justify-between text-xs font-semibold mb-1.5">
                        <span className="text-[#cbd5e1]">Max Per-Transaction Limit</span>
                        <span className="font-mono text-[#00f2fe]">{maxPerTx.toFixed(2)} USDC</span>
                      </div>
                      <input 
                        type="range" 
                        min="0.01" 
                        max="0.50" 
                        step="0.01" 
                        value={maxPerTx}
                        onChange={(e) => setMaxPerTx(parseFloat(e.target.value))}
                        className="w-full accent-[#00f2fe] bg-[rgba(255,255,255,0.1)] h-1.5 rounded-lg cursor-pointer"
                      />
                    </div>

                    {/* Daily Limit control */}
                    <div>
                      <div className="flex justify-between text-xs font-semibold mb-1.5">
                        <span className="text-[#cbd5e1]">Daily Budget (24h Window)</span>
                        <span className="font-mono text-[#10b981]">{dailySpent.toFixed(2)} / {dailyLimit.toFixed(2)} USDC</span>
                      </div>
                      <div className="w-full h-2 rounded-full bg-[rgba(255,255,255,0.1)] overflow-hidden mb-1.5">
                        <div 
                          className={`h-full rounded-full transition-all ${dailySpent > dailyLimit ? "bg-[#ef4444]" : "bg-[#10b981]"}`} 
                          style={{ width: `${Math.min(100, (dailySpent / dailyLimit) * 100)}%` }}
                        ></div>
                      </div>
                      <input 
                        type="range" 
                        min="1.00" 
                        max="20.00" 
                        step="0.50" 
                        value={dailyLimit}
                        onChange={(e) => setDailyLimit(parseFloat(e.target.value))}
                        className="w-full accent-[#10b981] bg-[rgba(255,255,255,0.1)] h-1.5 rounded-lg cursor-pointer"
                      />
                    </div>

                    <div>
                      <div className="flex justify-between text-xs font-semibold mb-1.5">
                        <span className="text-[#cbd5e1]">Monthly Budget Limit</span>
                        <span className="font-mono text-[#a855f7]">12.00 / 100.00 USDC</span>
                      </div>
                      <div className="w-full h-2 rounded-full bg-[rgba(255,255,255,0.1)] overflow-hidden">
                        <div className="h-full bg-[#a855f7] rounded-full" style={{ width: "12%" }}></div>
                      </div>
                    </div>

                    {/* Test AI Sentinel Button */}
                    <div className="pt-4 border-t border-[rgba(255,255,255,0.08)]">
                      <button
                        onClick={async () => {
                          try {
                            await fetch(`${getApiUrl()}/api/sentinel/simulate-attack`, {
                              method: "POST",
                              headers: { "Content-Type": "application/json" },
                              body: JSON.stringify({ attackType: "PRICE_SPIKE_ANOMALY" })
                            });
                          } catch (e) {
                            console.error(e);
                          }
                        }}
                        className="w-full py-3 rounded-xl bg-[rgba(239,68,68,0.15)] hover:bg-[rgba(239,68,68,0.3)] text-[#ef4444] font-bold text-xs border border-[rgba(239,68,68,0.3)] hover:border-[#ef4444] transition-all flex items-center justify-center gap-2 shadow-[0_0_15px_rgba(239,68,68,0.2)]"
                      >
                        <ShieldAlert className="w-4 h-4 text-[#ef4444]" />
                        <span>🚨 Trigger AI Sentinel Attack Simulation (Test Circuit Breaker)</span>
                      </button>
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="mt-16 pt-6 border-t border-[rgba(255,255,255,0.08)] flex flex-col sm:flex-row items-center justify-between text-xs text-[#64748b] gap-4">
        <div className="flex items-center gap-2">
          <span className="font-bold text-[#cbd5e1]">AI Micropayment Network (AiMPN) v2.0</span>
          <span>•</span>
          <span>Powered by Base Mainnet (Chain ID: 8453)</span>
        </div>
        <div className="flex items-center gap-6">
          <a href="https://github.com/tdpeta754-design/ai-micropayment-network" target="_blank" rel="noreferrer" className="hover:text-white transition-colors">GitHub Repository</a>
          <a href="https://basescan.org/address/0xFdc195DB85a7178f44916E9A21Eb2A9c99Ba5fA6" target="_blank" rel="noreferrer" className="hover:text-white transition-colors">On-Chain Registry</a>
          <a href="https://github.com/tdpeta754-design/ai-micropayment-network/blob/main/AI_BUILDER_BOUNTY_PROGRAM.md" target="_blank" rel="noreferrer" className="hover:text-white transition-colors">Builder Bounty</a>
          <span className="text-[#00f2fe]">100% Zero-Gas Paymaster Active</span>
        </div>
      </footer>
    </div>
  );
}
