"use client";

import React, { useState, useEffect } from "react";
import { 
  ShieldCheck, 
  Zap, 
  Activity, 
  Cpu, 
  Database, 
  Lock, 
  ExternalLink, 
  RefreshCw, 
  ArrowRight, 
  CheckCircle2, 
  AlertCircle, 
  Layers, 
  Terminal, 
  DollarSign, 
  TrendingUp, 
  Clock, 
  Wifi, 
  WifiOff, 
  ShieldAlert, 
  Play, 
  Pause, 
  Server, 
  Settings,
  XCircle
} from "lucide-react";

// Dynamic host resolution for VPS / Cloud / Localhost environments
const getWsUrl = () => {
  if (typeof window !== "undefined" && process.env.NEXT_PUBLIC_WS_URL) {
    return process.env.NEXT_PUBLIC_WS_URL;
  }
  if (typeof window !== "undefined" && window.location.hostname !== "localhost") {
    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    return `${protocol}//${window.location.hostname}:3001`;
  }
  return "ws://localhost:3001";
};

const getApiUrl = () => {
  if (typeof window !== "undefined" && process.env.NEXT_PUBLIC_API_URL) {
    return process.env.NEXT_PUBLIC_API_URL;
  }
  if (typeof window !== "undefined" && window.location.hostname !== "localhost") {
    const protocol = window.location.protocol === "https:" ? "https:" : "http:";
    return `${protocol}//${window.location.hostname}:3001`;
  }
  return "http://localhost:3001";
};

interface Transaction {
  id: string;
  txHash: string;
  from: string;
  to: string;
  amountUsdc: string;
  purpose: string;
  timestamp: number;
  status: "completed" | "pending" | "failed" | "rejected";
}

interface ProviderService {
  id: string;
  name: string;
  agent: string;
  address: string;
  price: string;
  category: string;
  description: string;
  icon: string;
  responsePreview: any;
}

const AI_PROVIDERS: ProviderService[] = [
  {
    id: "serv-1",
    name: "AI Market Intelligence API",
    agent: "Agent B (Intelligence API)",
    address: "0x70F70567Ca2bfe6bD62d5bE38D09a04Ba16D575E",
    price: "0.050",
    category: "Market Analysis",
    description: "Real-time cryptocurrency sentiment, BTC/ETH prediction targets & confidence intervals.",
    icon: "📈",
    responsePreview: { sentiment: "BULLISH 🚀", btcTarget: "$98,500", confidence: "98.4%", recommendation: "STRONG_BUY" }
  },
  {
    id: "serv-2",
    name: "Global Meteorological Forecast",
    agent: "Agent C (Weather Oracle)",
    address: "0x33B101f3B82a7a42823a01C9028e3415D39e4412",
    price: "0.010",
    category: "Weather Data",
    description: "High-precision solar radiation and wind speed forecast for autonomous drone routing.",
    icon: "🌤️",
    responsePreview: { location: "Hanoi (21.0285° N, 105.8542° E)", temp: "34.5°C", condition: "Clear Sky", windSpeed: "12 km/h" }
  },
  {
    id: "serv-3",
    name: "GPU Tensor Core Lease",
    agent: "Agent D (Compute Cluster)",
    address: "0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7",
    price: "0.100",
    category: "Decentralized Compute",
    description: "10-minute dedicated lease on NVIDIA H100 GPU node for AI weights fine-tuning.",
    icon: "⚡",
    responsePreview: { leaseId: "lease-h100-992", nodeIp: "192.168.10.45:8000", allocatedVram: "80GB", expires: "+10 mins" }
  },
  {
    id: "serv-4",
    name: "LLM Token Inference Stream",
    agent: "Agent E (DeepSeek Router)",
    address: "0x44201b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a",
    price: "0.025",
    category: "AI Model API",
    description: "1,000 token inference batch generated by DeepSeek-R1-Agent reasoning engine.",
    icon: "🧠",
    responsePreview: { model: "deepseek-r1-agent", tokensUsed: 1000, latency: "84ms", output: "Optimal routing path verified via zero-knowledge proofs." }
  }
];

export default function DashboardPage() {
  const [mounted, setMounted] = useState<boolean>(false);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [wsConnected, setWsConnected] = useState<boolean>(false);
  const [isSimulating, setIsSimulating] = useState<boolean>(false);
  const [simulationStep, setSimulationStep] = useState<number>(0);
  const [simulatedData, setSimulatedData] = useState<any>(null);
  const [rejectionError, setRejectionError] = useState<string | null>(null);
  
  // Interactive Policy Controls
  const [isFrozen, setIsFrozen] = useState<boolean>(false);
  const [maxPerTx, setMaxPerTx] = useState<number>(0.10);
  const [dailyLimit, setDailyLimit] = useState<number>(10.00);
  const [dailySpent, setDailySpent] = useState<number>(2.40);
  
  const [stats, setStats] = useState({
    totalVolume: 412.850,
    totalTxCount: 1428,
    avgLatency: "142ms",
  });

  useEffect(() => {
    setMounted(true);
    const now = Date.now();
    setTransactions([
      {
        id: "tx-101",
        txHash: "0x8f2a1b3c4e5d6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b",
        from: "0xA100000000000000000000000000000000000001",
        to: "0x70F70567Ca2bfe6bD62d5bE38D09a04Ba16D575E",
        amountUsdc: "0.050",
        purpose: "AI Market Intelligence Data",
        timestamp: now - 45000,
        status: "completed"
      },
      {
        id: "tx-102",
        txHash: "0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d",
        from: "0xA100000000000000000000000000000000000001",
        to: "0x33B101f3B82a7a42823a01C9028e3415D39e4412",
        amountUsdc: "0.010",
        purpose: "Global Meteorological Forecast",
        timestamp: now - 120000,
        status: "completed"
      },
      {
        id: "tx-103",
        txHash: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
        from: "0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7",
        to: "0x70F70567Ca2bfe6bD62d5bE38D09a04Ba16D575E",
        amountUsdc: "0.025",
        purpose: "LLM Token Inference Stream",
        timestamp: now - 300000,
        status: "completed"
      },
      {
        id: "tx-104",
        txHash: "0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f",
        from: "0xA100000000000000000000000000000000000001",
        to: "0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7",
        amountUsdc: "0.100",
        purpose: "GPU Tensor Core Lease",
        timestamp: now - 600000,
        status: "completed"
      }
    ]);
  }, []);

  // WebSocket connection to Backend Indexer
  useEffect(() => {
    let ws: WebSocket | null = null;
    let reconnectTimer: NodeJS.Timeout;

    const connectWs = () => {
      try {
        ws = new WebSocket(getWsUrl());
        
        ws.onopen = () => {
          setWsConnected(true);
        };

        ws.onmessage = (event) => {
          try {
            const message = JSON.parse(event.data);
            if (message.type === "NEW_TRANSACTION" && message.data) {
              const newTx: Transaction = {
                id: "tx-" + Date.now(),
                txHash: message.data.txHash || "0x" + Math.random().toString(16).slice(2),
                from: message.data.from || "0xA100...0001",
                to: message.data.to || "0x70F7...575E",
                amountUsdc: message.data.amountUsdc || "0.050",
                purpose: message.data.purpose || "AI Micropayment",
                timestamp: Date.now(),
                status: "completed"
              };

              setTransactions(prev => [newTx, ...prev.slice(0, 19)]);
              setStats(prev => ({
                ...prev,
                totalVolume: parseFloat((prev.totalVolume + parseFloat(newTx.amountUsdc)).toFixed(3)),
                totalTxCount: prev.totalTxCount + 1
              }));
              setDailySpent(prev => parseFloat((prev + parseFloat(newTx.amountUsdc)).toFixed(3)));
            } else if (message.type === "SENTINEL_ALERT" && message.data) {
              const newTx: Transaction = {
                id: "alert-" + Date.now(),
                txHash: message.data.alertId || "0xALERT" + Math.random().toString(16).slice(2),
                from: message.data.targetWallet || "0x70F7...575E",
                to: "AI_SENTINEL_WARDEN",
                amountUsdc: "0.000",
                purpose: `🚨 [CIRCUIT BREAKER] ${message.data.threatType}: ${message.data.details}`,
                timestamp: Date.now(),
                status: "failed"
              };
              setTransactions(prev => [newTx, ...prev.slice(0, 19)]);
              setRejectionError(`🚨 [AI Sentinel Warden] Automated Circuit Breaker Engaged! Target: ${message.data.targetWallet} | Threat: ${message.data.threatType} | Action: ON_CHAIN_PAUSE (<100ms)`);
            }
          } catch (e) {
            console.error("Error parsing WebSocket message:", e);
          }
        };

        ws.onclose = () => {
          setWsConnected(false);
          reconnectTimer = setTimeout(connectWs, 5000);
        };

        ws.onerror = () => {
          setWsConnected(false);
        };
      } catch (e) {
        setWsConnected(false);
      }
    };

    connectWs();

    return () => {
      if (ws) ws.close();
      if (reconnectTimer) clearTimeout(reconnectTimer);
    };
  }, []);

  // Trigger x402 Simulation Flow
  const handleTriggerPayment = async (service: ProviderService) => {
    if (isSimulating) return;
    setIsSimulating(true);
    setSimulationStep(1);
    setSimulatedData(null);
    setRejectionError(null);

    // Step 1: Request without auth -> 402
    await new Promise(resolve => setTimeout(resolve, 600));
    setSimulationStep(2);

    // Guardrail Check 1: Is wallet frozen?
    if (isFrozen) {
      await new Promise(resolve => setTimeout(resolve, 600));
      setRejectionError("🚨 [Guardian Enforcer] Transaction REJECTED: Smart Wallet is currently FROZEN by Owner! Error Code: 0x4e487b71 (GuardrailTriggered)");
      setIsSimulating(false);
      setSimulationStep(0);
      return;
    }

    // Guardrail Check 2: Exceeds Max Per-Transaction Limit?
    if (parseFloat(service.price) > maxPerTx) {
      await new Promise(resolve => setTimeout(resolve, 600));
      setRejectionError(`🚨 [Guardian Enforcer] Transaction REJECTED: Price (${service.price} USDC) exceeds Max Per-Tx Limit (${maxPerTx.toFixed(2)} USDC)! Error Code: 0x1f2a3b4c (ExceedsPerTxLimit)`);
      setIsSimulating(false);
      setSimulationStep(0);
      return;
    }

    // Guardrail Check 3: Exceeds Daily Limit?
    if (dailySpent + parseFloat(service.price) > dailyLimit) {
      await new Promise(resolve => setTimeout(resolve, 600));
      setRejectionError(`🚨 [Guardian Enforcer] Transaction REJECTED: Price would exceed Daily Limit (${dailyLimit.toFixed(2)} USDC)! Error Code: 0x8c9d0e1f (ExceedsDailyLimit)`);
      setIsSimulating(false);
      setSimulationStep(0);
      return;
    }

    // Step 2: Auto-Pay Engine Triggered -> Sign & Submit
    await new Promise(resolve => setTimeout(resolve, 800));
    setSimulationStep(3);

    // Step 3: Verify & Get PoP JWT Token
    await new Promise(resolve => setTimeout(resolve, 800));
    setSimulationStep(4);

    // Step 4: Retry Request with Bearer Token -> Success
    await new Promise(resolve => setTimeout(resolve, 700));
    setSimulationStep(5);
    setSimulatedData(service.responsePreview);

    // Add transaction to UI feed
    const simTx: Transaction = {
      id: "tx-" + Date.now(),
      txHash: "0x" + Array.from({length: 64}, () => Math.floor(Math.random() * 16).toString(16)).join(""),
      from: "0xA100000000000000000000000000000000000001",
      to: service.address,
      amountUsdc: service.price,
      purpose: service.name,
      timestamp: Date.now(),
      status: "completed"
    };

    setTransactions(prev => [simTx, ...prev.slice(0, 19)]);
    setStats(prev => ({
      ...prev,
      totalVolume: parseFloat((prev.totalVolume + parseFloat(service.price)).toFixed(3)),
      totalTxCount: prev.totalTxCount + 1
    }));
    setDailySpent(prev => parseFloat((prev + parseFloat(service.price)).toFixed(3)));

    // Reset simulation status after 4 seconds
    setTimeout(() => {
      setIsSimulating(false);
      setSimulationStep(0);
    }, 4500);
  };

  const formatTime = (ts: number) => {
    if (!mounted) return "Just now";
    const diffSeconds = Math.floor((Date.now() - ts) / 1000);
    if (diffSeconds < 60) return `${diffSeconds}s ago`;
    const diffMinutes = Math.floor(diffSeconds / 60);
    if (diffMinutes < 60) return `${diffMinutes}m ago`;
    return `${Math.floor(diffMinutes / 60)}h ago`;
  };

  return (
    <div className="min-h-screen px-4 md:px-8 py-6 max-w-[1600px] mx-auto">
      {/* Top Header / Nav */}
      <header className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 mb-8 pb-6 border-b border-[rgba(255,255,255,0.08)]">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-[#00f2fe] to-[#4facfe] flex items-center justify-center shadow-[0_0_25px_rgba(0,242,254,0.4)]">
            <Zap className="w-6 h-6 text-[#070a13] fill-[#070a13]" />
          </div>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-white">
                AI Micropayment Network
              </h1>
              <span className="badge badge-cyan">
                Base Sepolia L2
              </span>
            </div>
            <p className="text-sm text-[#94a3b8] mt-1 flex items-center gap-2">
              <span>Autonomous M2M Economy</span>
              <span>•</span>
              <span className="text-[#00f2fe] font-mono">ERC-4337 v0.6 Account Abstraction</span>
            </p>
          </div>
        </div>

        {/* Network & Live Status */}
        <div className="flex flex-wrap items-center gap-4">
          <div className="glass-card px-4 py-2.5 flex items-center gap-3">
            <div className="flex items-center gap-2">
              {wsConnected ? (
                <>
                  <span className="status-dot animate-pulse"></span>
                  <span className="text-xs font-semibold uppercase tracking-wider text-[#10b981] flex items-center gap-1">
                    <Wifi className="w-3.5 h-3.5" /> WebSocket Live
                  </span>
                </>
              ) : (
                <>
                  <span className="w-2 h-2 rounded-full bg-[#f59e0b]"></span>
                  <span className="text-xs font-semibold uppercase tracking-wider text-[#f59e0b] flex items-center gap-1">
                    <WifiOff className="w-3.5 h-3.5" /> Simulation Feed
                  </span>
                </>
              )}
            </div>
            <div className="h-4 w-[1px] bg-[rgba(255,255,255,0.1)]"></div>
            <span className="text-xs font-mono text-[#94a3b8]">Chain ID: 84532</span>
          </div>

          <button 
            onClick={() => handleTriggerPayment(AI_PROVIDERS[0])}
            disabled={isSimulating}
            className="btn-glow-cyan"
          >
            <Zap className={`w-5 h-5 ${isSimulating ? "animate-spin" : ""}`} />
            <span>{isSimulating ? "Executing x402 Pay..." : "⚡ Trigger AI Micropayment"}</span>
          </button>
        </div>
      </header>

      {/* Rejection Alert Banner */}
      {rejectionError && (
        <div className="p-4 rounded-xl bg-[rgba(239,68,68,0.15)] border border-[rgba(239,68,68,0.4)] text-[#fca5a5] flex items-center justify-between mb-8 animate-slide-in">
          <div className="flex items-center gap-3">
            <ShieldAlert className="w-6 h-6 text-[#ef4444] shrink-0" />
            <div className="text-sm font-semibold font-mono">{rejectionError}</div>
          </div>
          <button onClick={() => setRejectionError(null)} className="text-[#94a3b8] hover:text-white">
            <XCircle className="w-5 h-5" />
          </button>
        </div>
      )}

      {/* Stats Banner Grid */}
      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <div className="glass-card p-5">
          <div className="flex items-center justify-between text-[#94a3b8] mb-2">
            <span className="text-sm font-medium">Total Volume Settled</span>
            <DollarSign className="w-5 h-5 text-[#00f2fe]" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-3xl font-bold font-mono text-white">${mounted ? stats.totalVolume.toLocaleString("en-US", { minimumFractionDigits: 3 }) : "412.850"}</span>
            <span className="text-sm font-semibold text-[#10b981]">USDC</span>
          </div>
          <div className="flex items-center gap-1 text-xs text-[#10b981] mt-2">
            <TrendingUp className="w-3.5 h-3.5" />
            <span>+18.4% last 24h</span>
          </div>
        </div>

        <div className="glass-card p-5">
          <div className="flex items-center justify-between text-[#94a3b8] mb-2">
            <span className="text-sm font-medium">Autonomous Transactions</span>
            <Activity className="w-5 h-5 text-[#4facfe]" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-3xl font-bold font-mono text-white">{mounted ? stats.totalTxCount.toLocaleString("en-US") : "1,428"}</span>
            <span className="text-sm text-[#94a3b8]">calls</span>
          </div>
          <div className="flex items-center gap-1 text-xs text-[#94a3b8] mt-2">
            <span>Zero human intervention</span>
          </div>
        </div>

        <div className="glass-card p-5">
          <div className="flex items-center justify-between text-[#94a3b8] mb-2">
            <span className="text-sm font-medium">Average M2M Latency</span>
            <Clock className="w-5 h-5 text-[#a855f7]" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-3xl font-bold font-mono text-white">{stats.avgLatency}</span>
            <span className="text-sm text-[#10b981]">sub-second</span>
          </div>
          <div className="flex items-center gap-1 text-xs text-[#a855f7] mt-2">
            <span>Optimized Base L2 Routing</span>
          </div>
        </div>

        <div className="glass-card p-5">
          <div className="flex items-center justify-between text-[#94a3b8] mb-2">
            <span className="text-sm font-medium">Gas Paymaster (ERC-4337)</span>
            <ShieldCheck className="w-5 h-5 text-[#10b981]" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-2xl font-bold text-[#10b981]">Active (Sponsored)</span>
          </div>
          <div className="flex items-center gap-1 text-xs text-[#94a3b8] mt-2">
            <span>AI Agents pay 0 ETH for gas</span>
          </div>
        </div>
      </section>

      {/* Mobile Executive Analytics & Financial Reports (For Solo Founder VIP Monitoring) */}
      <section className="glass-card p-6 mb-8 border-[rgba(168,85,247,0.3)] bg-gradient-to-r from-[rgba(168,85,247,0.08)] to-[rgba(0,242,254,0.05)] shadow-[0_0_20px_rgba(168,85,247,0.15)]">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 pb-4 border-b border-[rgba(255,255,255,0.08)]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-[rgba(168,85,247,0.2)] border border-[#a855f7] flex items-center justify-center text-[#a855f7] font-bold shrink-0 shadow-[0_0_15px_rgba(168,85,247,0.3)]">
              📱
            </div>
            <div>
              <h2 className="text-lg md:text-xl font-bold text-white tracking-tight flex items-center gap-2">
                <span>Mobile Executive Analytics & Financial Reports</span>
                <span className="badge badge-purple text-[10px]">PWA READY</span>
              </h2>
              <p className="text-xs text-[#94a3b8]">Báo cáo Doanh thu, Lượng truy cập và Hiệu suất Nền kinh tế cho Founder (Ngày / Tuần / Tháng / Quý)</p>
            </div>
          </div>
          <div className="text-xs font-mono text-[#00f2fe] bg-[rgba(0,242,254,0.1)] px-3 py-1.5 rounded-lg border border-[rgba(0,242,254,0.2)] flex items-center gap-2 w-fit">
            <span className="w-2 h-2 rounded-full bg-[#10b981] animate-pulse"></span>
            <span>Live Sync: 100% Uptime</span>
          </div>
        </div>

        {/* 4 Timeframe Cards Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
          <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(0,242,254,0.4)] transition-all">
            <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
              <span>🌞 Hôm nay (Daily)</span>
              <span className="text-[#10b981] font-bold">+15.2%</span>
            </div>
            <div className="text-2xl font-bold font-mono text-white mb-2">$12.500 <span className="text-xs text-[#00f2fe] font-normal">USDC</span></div>
            <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
              <span>Truy cập API: <b className="text-white">250 calls</b></span>
              <span className="text-[#10b981]">0 Gas</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(79,172,254,0.4)] transition-all">
            <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
              <span>📅 Tuần này (Weekly)</span>
              <span className="text-[#10b981] font-bold">+32.4%</span>
            </div>
            <div className="text-2xl font-bold font-mono text-white mb-2">$87.500 <span className="text-xs text-[#4facfe] font-normal">USDC</span></div>
            <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
              <span>Truy cập API: <b className="text-white">1,750 calls</b></span>
              <span className="text-[#00f2fe]">14 Agents</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(168,85,247,0.4)] transition-all">
            <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
              <span>🗓️ Tháng này (Monthly)</span>
              <span className="text-[#10b981] font-bold">+45.8%</span>
            </div>
            <div className="text-2xl font-bold font-mono text-white mb-2">$375.000 <span className="text-xs text-[#a855f7] font-normal">USDC</span></div>
            <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
              <span>Truy cập API: <b className="text-white">7,500 calls</b></span>
              <span className="text-[#a855f7]">5 Blocked Attacks</span>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] hover:border-[rgba(16,185,129,0.4)] transition-all">
            <div className="flex items-center justify-between text-xs text-[#94a3b8] mb-1">
              <span>📈 Quý III/2026 (Quarterly)</span>
              <span className="text-[#10b981] font-bold">Q3 Target</span>
            </div>
            <div className="text-2xl font-bold font-mono text-[#10b981] mb-2">$1,125.00 <span className="text-xs text-white font-normal">USDC</span></div>
            <div className="flex items-center justify-between text-[11px] text-[#94a3b8] border-t border-[rgba(255,255,255,0.05)] pt-2">
              <span>Tổng truy cập: <b className="text-white">22,500 calls</b></span>
              <span className="text-[#10b981]">0.045 ETH Pool</span>
            </div>
          </div>
        </div>

        {/* PWA Mobile Installation Instruction Banner */}
        <div className="p-4 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)] flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-[#a855f7] flex items-center justify-center text-white text-xs font-bold shrink-0">
              PWA
            </div>
            <div className="text-xs text-[#cbd5e1]">
              <b className="text-white">💡 Hướng dẫn cài đặt App lên điện thoại (iPhone & Android):</b> Mở trình duyệt Safari/Chrome trên điện thoại truy cập vào link Dashboard $\rightarrow$ Chọn trình đơn (Menu) $\rightarrow$ Nhấn <b>"Thêm vào màn hình chính" (Add to Home Screen)</b>. Ứng dụng sẽ chạy độc lập full-screen như App chính chủ mà không cần tải từ App Store!
            </div>
          </div>
          <span className="text-[11px] font-mono text-[#a855f7] border border-[#a855f7] px-3 py-1 rounded-lg shrink-0">
            Zero App Store Fees
          </span>
        </div>
      </section>

      {/* Interactive Simulator Flow Banner (Visible during simulation) */}
      {isSimulating && (
        <section className="glass-card p-6 mb-8 border-[rgba(0,242,254,0.4)] bg-[rgba(0,242,254,0.05)] animate-slide-in">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="w-3 h-3 rounded-full bg-[#00f2fe] animate-ping"></div>
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                <span>⚡ x402 Auto-Payment Engine — Live M2M Negotiation</span>
              </h3>
            </div>
            <span className="text-xs font-mono px-3 py-1 rounded-full bg-[rgba(0,242,254,0.15)] text-[#00f2fe] border border-[rgba(0,242,254,0.3)]">
              Step {simulationStep} of 5
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-5 gap-3">
            {[
              { step: 1, title: "1. HTTP Request", desc: "Agent A requests API data", icon: <ArrowRight className="w-4 h-4" /> },
              { step: 2, title: "2. HTTP 402 Pay Req", desc: "Provider requires USDC payment", icon: <Lock className="w-4 h-4" /> },
              { step: 3, title: "3. On-chain Pay", desc: "Router transfers USDC on Base", icon: <RefreshCw className="w-4 h-4 animate-spin" /> },
              { step: 4, title: "4. PoP Token Issued", desc: "JWT signed by indexer", icon: <CheckCircle2 className="w-4 h-4" /> },
              { step: 5, title: "5. Data Unlocked", desc: "Authorization Bearer success", icon: <Zap className="w-4 h-4" /> },
            ].map((s) => {
              const isActive = simulationStep === s.step;
              const isDone = simulationStep > s.step;
              return (
                <div 
                  key={s.step} 
                  className={`p-4 rounded-xl border transition-all ${
                    isActive 
                      ? "bg-[rgba(0,242,254,0.15)] border-[#00f2fe] shadow-[0_0_15px_rgba(0,242,254,0.3)] scale-105" 
                      : isDone 
                      ? "bg-[rgba(16,185,129,0.1)] border-[rgba(16,185,129,0.3)] text-[#10b981]" 
                      : "bg-[rgba(255,255,255,0.02)] border-[rgba(255,255,255,0.08)] opacity-40"
                  }`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-bold font-mono">{s.title}</span>
                    {isDone ? <CheckCircle2 className="w-4 h-4 text-[#10b981]" /> : s.icon}
                  </div>
                  <p className="text-xs text-[#94a3b8] mt-1">{s.desc}</p>
                </div>
              );
            })}
          </div>

          {simulatedData && (
            <div className="mt-5 p-4 rounded-xl bg-[rgba(16,185,129,0.1)] border border-[rgba(16,185,129,0.3)] flex items-center justify-between animate-slide-in">
              <div className="flex items-center gap-3">
                <CheckCircle2 className="w-6 h-6 text-[#10b981]" />
                <div>
                  <div className="text-sm font-bold text-white">🎉 Autonomous AI Transaction Completed Successfully!</div>
                  <div className="text-xs text-[#94a3b8] mt-0.5 font-mono">Received AI Payload: {JSON.stringify(simulatedData)}</div>
                </div>
              </div>
              <span className="badge badge-emerald">Payment Settled</span>
            </div>
          )}
        </section>
      )}

      {/* AI Provider Marketplace Directory */}
      <section className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Server className="w-5 h-5 text-[#00f2fe]" />
            <h2 className="text-lg font-bold text-white">AI Service Marketplace (x402 Provider Directory)</h2>
          </div>
          <span className="text-xs text-[#94a3b8]">Click any service to test autonomous M2M purchasing</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {AI_PROVIDERS.map((srv) => (
            <div key={srv.id} className="glass-card p-5 flex flex-col justify-between border-[rgba(255,255,255,0.08)] hover:border-[rgba(0,242,254,0.4)] transition-all group">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-3xl">{srv.icon}</span>
                  <span className="text-xs font-mono font-bold px-2.5 py-1 rounded-full bg-[rgba(0,242,254,0.1)] text-[#00f2fe] border border-[rgba(0,242,254,0.2)]">
                    {srv.price} USDC
                  </span>
                </div>
                <h3 className="text-base font-bold text-white group-hover:text-[#00f2fe] transition-colors mb-1">{srv.name}</h3>
                <div className="text-xs font-semibold text-[#a855f7] mb-2">{srv.agent}</div>
                <p className="text-xs text-[#94a3b8] leading-relaxed mb-4">{srv.description}</p>
              </div>

              <button 
                onClick={() => handleTriggerPayment(srv)}
                disabled={isSimulating}
                className="w-full py-2 rounded-xl bg-[rgba(255,255,255,0.05)] hover:bg-[rgba(0,242,254,0.2)] text-white font-semibold text-xs border border-[rgba(255,255,255,0.1)] hover:border-[#00f2fe] transition-all flex items-center justify-center gap-2 group-hover:shadow-[0_0_15px_rgba(0,242,254,0.2)]"
              >
                <Zap className="w-3.5 h-3.5 text-[#00f2fe]" />
                <span>Trigger x402 Buy</span>
              </button>
            </div>
          ))}
        </div>
      </section>

      {/* Main 2-Column Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column (5 Cols) — AI Wallets & Security Guardrails */}
        <div className="lg:col-span-5 flex flex-col gap-6">
          
          {/* Agent A Card */}
          <div className="glass-card p-6 border-l-4 border-l-[#00f2fe]">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[rgba(0,242,254,0.15)] flex items-center justify-center text-[#00f2fe] border border-[rgba(0,242,254,0.3)]">
                  <Cpu className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-white text-base">Agent A (Hedge Fund Bot)</h3>
                  <span className="text-xs text-[#94a3b8]">Role: Autonomous Consumer</span>
                </div>
              </div>
              <span className="badge badge-cyan">Active Account</span>
            </div>

            <div className="p-3 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] font-mono text-xs text-[#cbd5e1] mb-4 flex items-center justify-between">
              <span>0xA100...0001 (CREATE2)</span>
              <a href="https://sepolia.basescan.org" target="_blank" rel="noreferrer" className="text-[#00f2fe] hover:underline flex items-center gap-1 text-[11px]">
                <span>BaseScan</span>
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>

            <div className="grid grid-cols-2 gap-3 mb-4">
              <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                <div className="text-xs text-[#94a3b8]">USDC Balance</div>
                <div className="text-lg font-bold font-mono text-[#00f2fe] mt-1">100.00 USDC</div>
              </div>
              <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                <div className="text-xs text-[#94a3b8]">ETH Gas Balance</div>
                <div className="text-lg font-bold font-mono text-white mt-1">1.50 ETH</div>
              </div>
            </div>

            <div className="flex items-center justify-between text-xs text-[#94a3b8] pt-3 border-t border-[rgba(255,255,255,0.08)]">
              <span className="flex items-center gap-1.5 text-[#10b981]">
                <ShieldCheck className="w-4 h-4" /> Session Key Enabled
              </span>
              <span>Valid until: +24h</span>
            </div>
          </div>

          {/* Security Guardrails Panel with Interactive Controls */}
          <div className="glass-card p-6 border-l-4 border-l-[#10b981]">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2 text-white font-bold text-base">
                <ShieldCheck className="w-5 h-5 text-[#10b981]" />
                <span>Guardian Spending Policy</span>
              </div>
              <button
                onClick={() => setIsFrozen(!isFrozen)}
                className={`px-3 py-1.5 rounded-xl font-bold text-xs flex items-center gap-1.5 transition-all ${
                  isFrozen 
                    ? "bg-[#ef4444] text-white shadow-[0_0_15px_rgba(239,68,68,0.5)] animate-pulse" 
                    : "bg-[rgba(255,255,255,0.05)] text-[#cbd5e1] hover:bg-[rgba(239,68,68,0.2)] hover:text-[#ef4444]"
                }`}
              >
                {isFrozen ? <Play className="w-3.5 h-3.5" /> : <Pause className="w-3.5 h-3.5" />}
                <span>{isFrozen ? "🚨 FROZEN (Click to Unfreeze)" : "Freeze Wallets"}</span>
              </button>
            </div>

            <p className="text-xs text-[#94a3b8] mb-5">
              Enforced on-chain by <code className="text-[#00f2fe]">SmartWallet.sol</code> to prevent autonomous AI bugs from draining funds. Try adjusting sliders or freezing wallet!
            </p>

            <div className="space-y-5">
              {/* Max per tx control */}
              <div>
                <div className="flex justify-between text-xs font-semibold mb-1.5">
                  <span className="text-[#cbd5e1]">Max Per-Transaction Limit</span>
                  <span className="font-mono text-[#00f2fe]">{maxPerTx.toFixed(2)} USDC</span>
                </div>
                <input 
                  type="range" 
                  min="0.01" 
                  max="0.50" 
                  step="0.01" 
                  value={maxPerTx}
                  onChange={(e) => setMaxPerTx(parseFloat(e.target.value))}
                  className="w-full accent-[#00f2fe] bg-[rgba(255,255,255,0.1)] h-1.5 rounded-lg cursor-pointer"
                />
              </div>

              {/* Daily Limit control */}
              <div>
                <div className="flex justify-between text-xs font-semibold mb-1.5">
                  <span className="text-[#cbd5e1]">Daily Budget (24h Window)</span>
                  <span className="font-mono text-[#10b981]">{dailySpent.toFixed(2)} / {dailyLimit.toFixed(2)} USDC</span>
                </div>
                <div className="w-full h-2 rounded-full bg-[rgba(255,255,255,0.1)] overflow-hidden mb-1.5">
                  <div 
                    className={`h-full rounded-full transition-all ${dailySpent > dailyLimit ? "bg-[#ef4444]" : "bg-[#10b981]"}`} 
                    style={{ width: `${Math.min(100, (dailySpent / dailyLimit) * 100)}%` }}
                  ></div>
                </div>
                <input 
                  type="range" 
                  min="1.00" 
                  max="20.00" 
                  step="0.50" 
                  value={dailyLimit}
                  onChange={(e) => setDailyLimit(parseFloat(e.target.value))}
                  className="w-full accent-[#10b981] bg-[rgba(255,255,255,0.1)] h-1.5 rounded-lg cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs font-semibold mb-1.5">
                  <span className="text-[#cbd5e1]">Monthly Budget Limit</span>
                  <span className="font-mono text-[#a855f7]">12.00 / 100.00 USDC</span>
                </div>
                <div className="w-full h-2 rounded-full bg-[rgba(255,255,255,0.1)] overflow-hidden">
                  <div className="h-full bg-[#a855f7] rounded-full" style={{ width: "12%" }}></div>
                </div>
              </div>

              {/* Test AI Sentinel Button */}
              <div className="pt-2">
                <button
                  onClick={async () => {
                    try {
                      await fetch(`${getApiUrl()}/api/sentinel/simulate-attack`, {
                        method: "POST",
                        headers: { "Content-Type": "application/json" },
                        body: JSON.stringify({ attackType: "PRICE_SPIKE_ANOMALY" })
                      });
                    } catch (e) {
                      console.error(e);
                    }
                  }}
                  className="w-full py-2 rounded-xl bg-[rgba(239,68,68,0.15)] hover:bg-[rgba(239,68,68,0.3)] text-[#ef4444] font-bold text-xs border border-[rgba(239,68,68,0.3)] hover:border-[#ef4444] transition-all flex items-center justify-center gap-2 shadow-[0_0_10px_rgba(239,68,68,0.2)]"
                >
                  <ShieldAlert className="w-4 h-4 text-[#ef4444]" />
                  <span>🚨 Trigger AI Sentinel Attack Simulation</span>
                </button>
              </div>
            </div>
          </div>

          {/* Agent B Card */}
          <div className="glass-card p-6 border-l-4 border-l-[#a855f7]">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[rgba(168,85,247,0.15)] flex items-center justify-center text-[#d8b4fe] border border-[rgba(168,85,247,0.3)]">
                  <Database className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-white text-base">Agent B (Intelligence API)</h3>
                  <span className="text-xs text-[#94a3b8]">Role: AI Data Provider</span>
                </div>
              </div>
              <span className="badge badge-purple">Service Gate</span>
            </div>

            <div className="p-3 rounded-xl bg-[rgba(0,0,0,0.3)] border border-[rgba(255,255,255,0.06)] font-mono text-xs text-[#cbd5e1] mb-4 flex items-center justify-between">
              <span>0x70F7...575E (Deployer)</span>
              <a href="https://sepolia.basescan.org" target="_blank" rel="noreferrer" className="text-[#a855f7] hover:underline flex items-center gap-1 text-[11px]">
                <span>BaseScan</span>
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>

            <div className="grid grid-cols-2 gap-3 mb-4">
              <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                <div className="text-xs text-[#94a3b8]">Earned Revenue</div>
                <div className="text-lg font-bold font-mono text-[#a855f7] mt-1">312.85 USDC</div>
              </div>
              <div className="p-3 rounded-xl bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)]">
                <div className="text-xs text-[#94a3b8]">Base Price</div>
                <div className="text-lg font-bold font-mono text-white mt-1">0.05 USDC</div>
              </div>
            </div>

            <div className="flex items-center justify-between text-xs text-[#94a3b8] pt-3 border-t border-[rgba(255,255,255,0.08)]">
              <span>Protocol Fee: 0 bps (0%)</span>
              <span className="text-[#10b981] font-mono">HTTP 402 Active</span>
            </div>
          </div>

        </div>

        {/* Right Column (7 Cols) — Live WebSocket Transaction Stream */}
        <div className="lg:col-span-7 flex flex-col">
          <div className="glass-card p-6 flex-1 flex flex-col">
            <div className="flex items-center justify-between mb-6 pb-4 border-b border-[rgba(255,255,255,0.08)]">
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-[#00f2fe] animate-pulse"></div>
                <h2 className="text-lg font-bold text-white flex items-center gap-2">
                  <span>Live M2M Micropayment Feed</span>
                </h2>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs text-[#94a3b8] font-mono">Auto-refreshing</span>
              </div>
            </div>

            {/* Transactions List */}
            <div className="space-y-3 overflow-y-auto max-h-[720px] pr-1">
              {transactions.map((tx, idx) => (
                <div 
                  key={tx.id} 
                  className={`p-4 rounded-xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                    idx === 0 
                      ? "bg-[rgba(0,242,254,0.08)] border-[rgba(0,242,254,0.3)] shadow-[0_0_20px_rgba(0,242,254,0.1)] animate-slide-in" 
                      : "bg-[rgba(255,255,255,0.02)] border-[rgba(255,255,255,0.06)] hover:bg-[rgba(255,255,255,0.04)]"
                  }`}
                >
                  <div className="flex items-start gap-3.5">
                    <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 mt-0.5 ${
                      tx.purpose.includes("Weather") 
                        ? "bg-[rgba(16,185,129,0.15)] text-[#10b981] border border-[rgba(16,185,129,0.3)]" 
                        : tx.purpose.includes("Compute")
                        ? "bg-[rgba(245,158,11,0.15)] text-[#f59e0b] border border-[rgba(245,158,11,0.3)]"
                        : "bg-[rgba(0,242,254,0.15)] text-[#00f2fe] border border-[rgba(0,242,254,0.3)]"
                    }`}>
                      <Terminal className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-white">{tx.purpose}</span>
                        <span className="badge badge-cyan text-[10px] py-0 px-2">HTTP 402</span>
                      </div>
                      <div className="flex items-center gap-2 font-mono text-xs text-[#94a3b8] mt-1">
                        <span>{tx.from.slice(0, 6)}...{tx.from.slice(-4)}</span>
                        <ArrowRight className="w-3 h-3 text-[#64748b]" />
                        <span>{tx.to.slice(0, 6)}...{tx.to.slice(-4)}</span>
                        <span>•</span>
                        <span>{formatTime(tx.timestamp)}</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between sm:justify-end gap-4 shrink-0 border-t sm:border-t-0 pt-2 sm:pt-0 border-[rgba(255,255,255,0.06)]">
                    <div className="text-right">
                      <div className="text-base font-bold font-mono text-[#00f2fe]">+{tx.amountUsdc} USDC</div>
                      <div className="text-[11px] text-[#94a3b8]">Gas sponsored: 0 ETH</div>
                    </div>
                    <a 
                      href={`https://sepolia.basescan.org/tx/${tx.txHash}`} 
                      target="_blank" 
                      rel="noreferrer"
                      className="p-2 rounded-lg bg-[rgba(255,255,255,0.05)] hover:bg-[rgba(0,242,254,0.15)] text-[#94a3b8] hover:text-[#00f2fe] transition-colors"
                      title="View on BaseScan"
                    >
                      <ExternalLink className="w-4 h-4" />
                    </a>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-6 pt-4 border-t border-[rgba(255,255,255,0.08)] flex items-center justify-between text-xs text-[#94a3b8]">
              <span>Showing live M2M stream from PaymentRouter contract</span>
              <span className="font-mono text-[#00f2fe]">Verified via Proof-of-Payment JWT</span>
            </div>
          </div>
        </div>

      </div>

      {/* Footer */}
      <footer className="mt-12 pt-6 border-t border-[rgba(255,255,255,0.08)] flex flex-col sm:flex-row items-center justify-between text-xs text-[#64748b] gap-4">
        <div className="flex items-center gap-2">
          <span>AI Micropayment Network (AiMPN) v2.0</span>
          <span>•</span>
          <span className="text-[#94a3b8]">Built by Antigravity Team</span>
        </div>
        <div className="flex items-center gap-6">
          <a href="#" className="hover:text-white transition-colors">Documentation</a>
          <a href="#" className="hover:text-white transition-colors">Smart Contracts (GitHub)</a>
          <a href="#" className="hover:text-white transition-colors">Base Sepolia Faucet</a>
          <a href="#" className="hover:text-white transition-colors">Security Guardrails</a>
        </div>
      </footer>
    </div>
  );
}
